<?php

namespace common\lib\i18nModule;

use yii\base\InvalidConfigException;

/**
 * Class Module
 */
class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

    }

    /**
     * @inheritdoc
     */
    public $controllerNamespace = 'common\lib\i18nModule\controllers';

    /**
     * Translate shortcut
     *
     * @param $message
     * @param array $params
     * @param null $language
     *
     * @return string
     */
    public static function t($message, $params = [], $language = null)
    {
        return \Yii::t('metalguardian/i18n', $message, $params, $language);
    }

    /**
     * Url to the translation controller
     *
     * @return array
     */
    public static function getUrl()
    {
        return ['/i18n/translation/index'];
    }
}
