<?php
/**
 * Created by PhpStorm.
 * User: bahaaodeh
 * Date: 12/15/18
 * Time: 2:43 PM
 */

namespace common\components;


use yii\helpers\ArrayHelper;
use yii\web\Request;

class UrlManager extends \codemix\localeurls\UrlManager
{
    public $is_cli = false;


    public function init()
    {
        $this->rules = ArrayHelper::merge([
            'cdn/cache/<size:\w+>/<path:.+>' => 'image-resize/index',
        ], $this->rules);
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Parses the user request.
     * @param Request $request the request component
     * @return array|bool the route and the associated parameters. The latter is always empty
     * if [[enablePrettyUrl]] is `false`. `false` is returned if the current request cannot be successfully parsed.
     * @throws \yii\base\InvalidConfigException
     */
    public function parseRequest($request)
    {
        $pathInfo = rtrim($request->getPathInfo(), "/");
        $request->setPathInfo($pathInfo);
        $result = parent::parseRequest($request);
        return $result;
    }


    public function createUrl($params)
    {
        $url = parent::createUrl($params);
        ///@TODO need to know why create url return full url
        if ($this->is_cli) {
            $pos = strpos($url, $this->baseUrl);
            if ($pos !== false) {
                $url = substr_replace($url, '', $pos, strlen($this->baseUrl));
            }
        }
        return $url;
    }
}