<?php

namespace common\models;

use Yii;
use yii\caching\TagDependency;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "{{%user_type}}".
 *
 * @property int $id
 * @property string $name
 * @property int $status
 * @property string $created_at
 * @property int $created_by
 * @property string $updated_at
 * @property int $updated_by
 * @property int $is_deleted
 * @property string $deleted_at
 * @property int $deleted_by
 * @property string $ip_address
 * @property string $user_agent
 *
 * @property User[] $users
 */
class UserType extends \common\models\ActiveRecord
{
    const ADMIN = 1;
    const USER = 2;


    const CACHE_KEY = 'cache:tag:userType:list';
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user_type}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['status'], 'integer'],
           // [['created_at', 'updated_at', 'deleted_at'], 'safe'],
            [['name'], 'string', 'max' => 255],
            //[['ip_address'], 'string', 'max' => 40],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'status' => Yii::t('app', 'Status'),
            'created_at' => Yii::t('app', 'Created At'),
            'created_by' => Yii::t('app', 'Created By'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'updated_by' => Yii::t('app', 'Updated By'),
            'is_deleted' => Yii::t('app', 'Is Deleted'),
            'deleted_at' => Yii::t('app', 'Deleted At'),
            'deleted_by' => Yii::t('app', 'Deleted By'),
            'ip_address' => Yii::t('app', 'Ip Address'),
            'user_agent' => Yii::t('app', 'User Agent'),
        ];
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(User::className(), ['user_type_id' => 'id']);
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        TagDependency::invalidate(Yii::$app->cache,self::CACHE_KEY);
    }


    /**
     * @param bool $asArray
     * @return array|Country[]|\yii\db\ActiveRecord[]
     */
    public static function getCachedList($asArray=false){
        $list = self::find()->cache(0,new TagDependency(['tags' => self::CACHE_KEY]));
        if($asArray){
            $list->asArray();
        }
        return $list->all();
    }

    /**
     * @return array
     */
    public static function getNameList(){
        $list = self::getCachedList(true);
        return ArrayHelper::map($list,'id','name');
    }
    /**
     * @return array
     */
    public static function getPublicNameList(){
        $list = self::getCachedList(true);
        $list =  ArrayHelper::map($list,'id','name');
        unset($list[UserType::ADMIN]);
        return $list;
    }
}
