<?php
namespace common\migration;
/**
 * Created by PhpStorm.
 * User: bahaaodeh
 * Date: 4/15/18
 * Time: 12:32 PM
 */

class Migration extends \yii\db\Migration
{
    /**
     * @param string $table
     * @param array $columns
     * @param null $options
     * @param bool $withTrackingParams
     */
    public function createTable($table, $columns, $options = null,$withTrackingParams = true)
    {
        if ($options == null) {
            $options = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
        }
        if($withTrackingParams) {
            $columns = array_merge($columns, [
                'created_at' => 'datetime NOT NULL DEFAULT CURRENT_TIMESTAMP',
                'created_by' => 'int(11) DEFAULT NULL',
                'updated_at' => 'datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP',
                'updated_by' => 'int(11) DEFAULT NULL',
                'is_deleted' => $this->tinyInteger(1)->defaultValue(0)->notNull(),
                'deleted_at' => 'datetime DEFAULT NULL',
                'deleted_by' => 'int(11) DEFAULT NULL',
                'ip_address' => $this->string(40)->null(),
                'user_agent' => $this->string()->null()
            ]);

            parent::createTable($table, $columns, $options); // TODO: Change the autogenerated stub
            $table = str_replace(['{','}','%'],'',$table);

            //these relations for tracking only no need for foreign key
            //$this->addForeignKey($table . '_created_by_user', $table, 'created_by', 'user', 'id');
            //$this->addForeignKey($table . '_updated_by_user', $table, 'updated_by', 'user', 'id');
            //$this->addForeignKey($table . '_deleted_by_user', $table, 'deleted_by', 'user', 'id');
            $this->createIndex($table.'_is_deleted_index',$table,'is_deleted');
        }else{
            parent::createTable($table, $columns, $options); // TODO: Change the autogenerated stub
        }
    }
}