<?php
/**
 * Created by PhpStorm.
 * User: bahaaodeh
 * Date: 4/22/18
 * Time: 3:56 PM
 */

namespace backend\widgets;


use yii\web\JsExpression;

class TinyMce extends \dosamigos\tinymce\TinyMce
{
    public $clientOptions = [
        'plugins' => [
            "toc advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code fullscreen insertdatetime media table contextmenu paste"
        ],
        'extended_valid_elements' => '"iframe[src|title|width|height|allowfullscreen|frameborder|class|id|*],object[classid|width|height|codebase|*],param[name|value|_value|*],embed[type|width|height|src|*]"',
        'toolbar' => "toc insertfile undo redo | styleselect fontsizeselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link unlink image",
        'theme_modern_toolbar_location' => 'top',
        'theme_modern_toolbar_align' => 'right',
        'theme_modern_statusbar_location' => 'bottom',
        'toc_header' => 'h3',
        'toc_depth' => 6,
        'directionality' => 'rtl',
        'relative_urls' => false,
        'remove_script_host' => false,
        'convert_urls' => true,

    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->view->registerJs(<<<JS
        function file_browser_callback (field_name, url, type, win) {
		        tinymce.activeEditor.windowManager.open({
		            url: "/helper/file-browser?type=image&field_name="+field_name,
		            title : 'Select Image',
		            width: 782,
		            height: 500,
		            inline: "yes",
		            resizable : "yes",
		            close_previous: "no"
		        }, {
		            window: win,
		            input: field_name
		        });
       }
JS
        );

        if(empty($this->clientOptions['file_browser_callback'])){
            $this->clientOptions['file_browser_callback'] =   new JsExpression('file_browser_callback');
        }
    }

}